[NO-TICKET] Pin ruby-spec to avoid breakages related to modern Rubies
**What does this PR do?**

This PR pins the version of `ruby-spec` used by the
`ruby_dir_interruption_path` scenario to a known-good version.

This fixes the issue from
<https://github.com/DataDog/prof-correctness/actions/runs/26744158694/job/78815284046?pr=140>:

```
    correctness_test.go:31: Error running the test: docker run failed: exit status 1
        output: I, [2026-06-01T08:41:41.728271 #7]  INFO -- datadog: [datadog] DATADOG CONFIGURATION - CORE - {"date":"2026-06-01T08:41:41Z","os_name":"x86_64-pc-linux","version":"2.35.0.dev","lang":"ruby","lang_version":"3.3.11","env":null,"service":"prof-correctness-ruby_dir_interruption_patch","dd_version":null,"debug":false,"tags":null,"runtime_metrics_enabled":false,"vm":"ruby-3.3.11","health_metrics_enabled":false,"profiling_enabled":true,"dynamic_instrumentation_enabled":false}
        Dir interruption patch is present!
        ruby 3.3.11 (2026-03-26 revision 1f2d15125a) [x86_64-linux]
        ..........................................................................................................................................................................................................................................................................................................F................................

        1)
        Dir#pos is an alias of Dir#tell FAILED
        Expected #<UnboundMethod: Datadog::Profiling::Ext::DirInstanceMonkeyPatches#pos(*args, **kwargs, &block) /usr/local/bundle/bundler/gems/dd-trace-rb-d2be2410ee11/lib/datadog/profiling/ext/dir_monkey_patches.rb:418> == #<UnboundMethod: Datadog::Profiling::Ext::DirInstanceMonkeyPatches#tell(*args, **kwargs, &block) /usr/local/bundle/bundler/gems/dd-trace-rb-d2be2410ee11/lib/datadog/profiling/ext/dir_monkey_patches.rb:411>
        to be truthy but was false
        /app/spec-master/core/dir/pos_spec.rb:7:in `block (2 levels) in <top (required)>'
        /app/spec-master/core/dir/pos_spec.rb:5:in `<top (required)>'

        Finished in 0.900423 seconds

        34 files, 331 examples, 444 expectations, 1 failure, 0 errors, 0 tagged
```

This "issue" was caused by a ruby-spec change in
<https://github.com/ruby/spec/commit/8b6d6fd4e7ae43877bb19e951f3910a11243844f#diff-ecacfbabe71cb51153352e33560aeffdd9f76171b0efc48d421250dfebb5a0e3>
but rather than trying to follow that change, we decided that it's
easier to pin to a ruby-spec version that reflects 3.3, since anyway
in the future ruby-spec is going to drop 3.3 and below.

**Motivation:**

Fix breakage in prof-correctness.

**Additional Notes:**

N/A

**How to test the change?**

CI should be green again!