[PROF-12782] Fix Ruby scenarios failing due to API change
**What does this PR do?**

This PR updates the Ruby scenarios to use the correct API for getting profile
data (this API is needed for dd-trace-rb 2.15.0+).

Without this change, prof-correctness Ruby tests were failing with

```
W, [2025-10-01T12:01:33.611884 #7]  WARN -- datadog: [datadog] (/usr/local/bundle/bundler/gems/dd-trace-rb-9a8878fbfed8/lib/datadog/profiling/scheduler.rb:137:in `rescue in flush_events') Unable to report profile. Cause: NoMethodError undefined method `pprof_data' for an instance of Datadog::Profiling::Flush Location: main.rb:8:in `export'
```

**Motivation:**

Fix prof-correctness for Ruby!

**Additional Notes:**

The new API was introduced in https://github.com/DataDog/dd-trace-rb/pull/4569 to
match the libdatadog change in https://github.com/DataDog/libdatadog/pull/926 .

**How to test the change?**

I've locally validated the tests are back to green, and we should see the same in CI.